version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "9011:9011"
      - "9012:9012"
    depends_on:
      - "phpfpm"
    volumes:
      - "$PWD/nginx.conf:/etc/nginx/nginx.conf"
      - "$PWD/SSO-server:/usr/share/nginx/html/SSO-server"
      - "$PWD/website-A:/usr/share/nginx/html/website-A"
  phpfpm:
    build: ./phpfpm-Dockerfile
    volumes:
      - ./SSO-server:/usr/share/nginx/html/SSO-server
      - ./website-A:/usr/share/nginx/html/website-A
  mysql57:
    image: mysql:5.7
    ports:
      - "13396:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=demo_password