version: '3'
services:
  composer:
    build: ./phpcli-Dockerfile
    volumes:
      - ./SSO-server:/usr/share/nginx/html/SSO-server
      - ./website-A:/usr/share/nginx/html/website-A
    command: sh -c "cd /usr/share/nginx/html/SSO-server && composer install && cd /usr/share/nginx/html/website-A && composer install"
  phpfpm:
    build: ./phpfpm-Dockerfile
    depends_on:
      - composer
    volumes:
      - ./SSO-server:/usr/share/nginx/html/SSO-server
      - ./website-A:/usr/share/nginx/html/website-A
  web:
    image: nginx:1.17.4-alpine
    ports:
      - "9011:9011"
      - "9012:9012"
    depends_on:
      - "phpfpm"
    volumes:
      - "$PWD/nginx.conf:/etc/nginx/nginx.conf"
      - "$PWD/SSO-server:/usr/share/nginx/html/SSO-server"
      - "$PWD/website-A:/usr/share/nginx/html/website-A"
  mysql57:
    image: mysql:5.7
    ports:
      - "13396:3306"
    volumes:
      - ./mysql-schemas.sql:/docker-entrypoint-initdb.d/mysql-schemas.sql
    environment:
      - MYSQL_ROOT_PASSWORD=demo_password